# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pines.xdc

# Block Designs: bd/practica/practica.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==practica || ORIG_REF_NAME==practica} -quiet] -quiet

# IP: bd/practica/ip/practica_picoblaze_0_0/practica_picoblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==practica_picoblaze_0_0 || ORIG_REF_NAME==practica_picoblaze_0_0} -quiet] -quiet

# IP: bd/practica/ip/practica_ps2_0_0/practica_ps2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==practica_ps2_0_0 || ORIG_REF_NAME==practica_ps2_0_0} -quiet] -quiet

# IP: bd/practica/ip/practica_PWM_0_0/practica_PWM_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==practica_PWM_0_0 || ORIG_REF_NAME==practica_PWM_0_0} -quiet] -quiet

# IP: bd/practica/ip/practica_clk_wiz_1/practica_clk_wiz_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==practica_clk_wiz_1 || ORIG_REF_NAME==practica_clk_wiz_1} -quiet] -quiet

# XDC: bd/practica/practica_ooc.xdc
