# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniel/Documents/VHDL/practicaa/practicaa.srcs/sources_1/bd/practica/ip/practica_picoblaze_0_0/practica_picoblaze_0_0.xci
# IP: The module: 'practica_picoblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Documents/VHDL/practicaa/practicaa.srcs/sources_1/bd/practica/ip/practica_picoblaze_0_0/constrs_1/new/pines.xdc
# XDC: The top module name and the constraint reference have the same name: 'practica_picoblaze_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/daniel/Documents/VHDL/practicaa/practicaa.srcs/sources_1/bd/practica/ip/practica_picoblaze_0_0/practica_picoblaze_0_0.xci
# IP: The module: 'practica_picoblaze_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Documents/VHDL/practicaa/practicaa.srcs/sources_1/bd/practica/ip/practica_picoblaze_0_0/constrs_1/new/pines.xdc
# XDC: The top module name and the constraint reference have the same name: 'practica_picoblaze_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
