# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pines.xdc

# Block Designs: bd/uartsys/uartsys.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uartsys || ORIG_REF_NAME==uartsys} -quiet] -quiet

# IP: bd/uartsys/ip/uartsys_uartrx_0_0/uartsys_uartrx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uartsys_uartrx_0_0 || ORIG_REF_NAME==uartsys_uartrx_0_0} -quiet] -quiet

# IP: bd/uartsys/ip/uartsys_baudios_0_0/uartsys_baudios_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uartsys_baudios_0_0 || ORIG_REF_NAME==uartsys_baudios_0_0} -quiet] -quiet

# IP: bd/uartsys/ip/uartsys_clk_wiz_0_0/uartsys_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uartsys_clk_wiz_0_0 || ORIG_REF_NAME==uartsys_clk_wiz_0_0} -quiet] -quiet

# IP: bd/uartsys/ip/uartsys_uarttx_0_0/uartsys_uarttx_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uartsys_uarttx_0_0 || ORIG_REF_NAME==uartsys_uarttx_0_0} -quiet] -quiet

# XDC: bd/uartsys/uartsys_ooc.xdc
