# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/daniel/Documents/VHDL/zynqnuevo/zynqnuevo.srcs/sources_1/bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0.xci
# IP: The module: 'zynqprueba_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Documents/VHDL/zynqnuevo/zynqnuevo.srcs/sources_1/bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqprueba_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/daniel/Documents/VHDL/zynqnuevo/zynqnuevo.srcs/sources_1/bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqprueba_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/daniel/Documents/VHDL/zynqnuevo/zynqnuevo.srcs/sources_1/bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqprueba_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/daniel/Documents/VHDL/zynqnuevo/zynqnuevo.srcs/sources_1/bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0.xci
# IP: The module: 'zynqprueba_rst_ps7_0_100M_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/daniel/Documents/VHDL/zynqnuevo/zynqnuevo.srcs/sources_1/bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqprueba_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/daniel/Documents/VHDL/zynqnuevo/zynqnuevo.srcs/sources_1/bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqprueba_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: /home/daniel/Documents/VHDL/zynqnuevo/zynqnuevo.srcs/sources_1/bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'zynqprueba_rst_ps7_0_100M_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
