webtalk_init -webtalk_dir /home/osvaldomg/Documentos/VHDL/MAQUINAS DE ESTADO/maquina_2/maquina_2.sim/sim_1/behav/xsim/xsim.dir/maq_2_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov 27 13:05:18 2018" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "66686fc2-de88-4ee4-949f-33ac1ff53ebd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "214f021270a844bab3e4a26acacedc75" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 16.04.5 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD A8-6410 APU with AMD Radeon R5 Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1408.680 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "5.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.04_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "124108_KB" -context "xsim\\usage"
webtalk_transmit -clientid 25270613 -regid "" -xml /home/osvaldomg/Documentos/VHDL/MAQUINAS DE ESTADO/maquina_2/maquina_2.sim/sim_1/behav/xsim/xsim.dir/maq_2_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/osvaldomg/Documentos/VHDL/MAQUINAS DE ESTADO/maquina_2/maquina_2.sim/sim_1/behav/xsim/xsim.dir/maq_2_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/osvaldomg/Documentos/VHDL/MAQUINAS DE ESTADO/maquina_2/maquina_2.sim/sim_1/behav/xsim/xsim.dir/maq_2_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
