# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynqprueba/zynqprueba.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqprueba || ORIG_REF_NAME==zynqprueba} -quiet] -quiet

# IP: bd/zynqprueba/ip/zynqprueba_processing_system7_0_0/zynqprueba_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqprueba_processing_system7_0_0 || ORIG_REF_NAME==zynqprueba_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynqprueba/ip/zynqprueba_axi_gpio_0_0/zynqprueba_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqprueba_axi_gpio_0_0 || ORIG_REF_NAME==zynqprueba_axi_gpio_0_0} -quiet] -quiet

# IP: bd/zynqprueba/ip/zynqprueba_axi_gpio_1_0/zynqprueba_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqprueba_axi_gpio_1_0 || ORIG_REF_NAME==zynqprueba_axi_gpio_1_0} -quiet] -quiet

# IP: bd/zynqprueba/ip/zynqprueba_xbar_0/zynqprueba_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqprueba_xbar_0 || ORIG_REF_NAME==zynqprueba_xbar_0} -quiet] -quiet

# IP: bd/zynqprueba/ip/zynqprueba_auto_pc_0/zynqprueba_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqprueba_auto_pc_0 || ORIG_REF_NAME==zynqprueba_auto_pc_0} -quiet] -quiet

# IP: bd/zynqprueba/ip/zynqprueba_ps7_0_axi_periph_0/zynqprueba_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqprueba_ps7_0_axi_periph_0 || ORIG_REF_NAME==zynqprueba_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/zynqprueba/ip/zynqprueba_rst_ps7_0_100M_0/zynqprueba_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynqprueba_rst_ps7_0_100M_0 || ORIG_REF_NAME==zynqprueba_rst_ps7_0_100M_0} -quiet] -quiet

# XDC: bd/zynqprueba/zynqprueba_ooc.xdc
